server:
    port: 8080
    servlet:
     contextPath: /labdna    
spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_DATABASE_USER}:${MONGO_DATABASE_PASSWORD}@${MONGO_DATABASE_HOST}/${MONGO_DATABASE_NAME}